# Generated by Django 5.1 on 2025-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizeremail', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('datetime', models.TextField()),
                ('location', models.TextField()),
                ('eventtype', models.TextField()),
                ('category', models.TextField()),
                ('utubelink', models.TextField()),
            ],
        ),
    ]
